language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
env:
  secure: QNU5nLS5KPkmKPR0vPr5ewuK7sggL5br3L7/Wj3tbfvn2zJN2LTbF798eGORcjeuzHPyO+ORqMKAo0OVXbhLifivGcUz2oqvZn+JqnpFCLc3nCyDZyD3BL9gaN7R8KP1DvCFpashsKIqO9HAer3hX9wDywEJ39sOT4l0193WpXbLoiZR0atMcVDXhQzTe5CNcqYuvJxJ+BIw8a4mABBJdkUXujSgx/mrjCL4aDozsmXlb1B9TG6HBuYITq9633YJpkv77lVU+7X3Dy/r9oyz9gC71qGeJXD3+oZ2khvo/jh6k8es40KamoomkzUBKzsbzsqcrmeIlk2hvL8Lx1fpEAmQzfcX2md1INUxn9Hh1F9qqoRk9Ltwe2nyPJQeA/rE3st/61GKBUTzryEjlsrGwYHuPwRuweijRl8HAiuygCf4luqErEeafrJm+WUVM3i9Jnhq3A7+yCPG6fhlUpdF8/FB6JUM2jfnWLQ+KRE2pXKh5B7f99UTNXsGporDU7pG77cJgbCUlD4Mg5BzRwABnqnZ+81DZaM+JhL4U80PmsZYdZv+rqCImLsl7U1D3Exzj9K/ujXLwEJ9IIrd/aPh4EzI576bIfR5KTw/raJzqJI0/Tb4RkoedqzJgs/pAxMtvQi2mlpe2Ggdy4Gxq71Y0sT9xCtzofzrzeJyVXM3Ygw=
